### ISSUE TITLE
lnd through tor to slow for clients

### ISSUE THREAD

**Issue by feikede** [raymonostr/nip57-server#1]
Using that nip57-server I found that the invoice requests timeout sometimes. Looks like this is because of tor searching for new circles. I am using the lnd on a dial-up line. Any idea?
Thanks.

**Comment by raymonostr** [comment]
Nice feature - I'll do it, thanks

**Comment by raymonostr** [comment]
Implemented with 8cf5c8681c411dbcb99fd325f101c05d79409323 - closing
